Algoritmo"Terreno"

Var
largura, comprimento,metroQuadrado,areaTerreno,precoTerreno: inteiro


Inicio

escreva("Digite a largura do terreno:")
leia(largura)
escreva("Digite o comprimento do terreno:")
leia(comprimento)
escreva("Digite o valor do metro quadrado:")
leia(metroQuadrado)
escreval

areaTerreno<- largura * comprimento
precoTerreno<- areaTerreno* metroQuadrado

escreva("Area do terreno:", areaTerreno)
escreva("Preco Terreno:", precoTerreno)

Fimalgoritmo